// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yrkltpxwqczebxqlzjxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlya2x0cHh3cWN6ZWJ4cWx6anhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0MDg3OTAsImV4cCI6MjA2ODk4NDc5MH0.TX2a59VhIGvQTVJhAgAlc88YIsGbdkQsaH2-UBCERrM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});